#!/usr/bin/env python3
"""
Embed all files in src/static into the firmware as binary assets, and generate src/_static_files.h
with declarations and a catalog for runtime access.
"""

import inspect
import os
import re
import shutil
from typing import Any

# PlatformIO/SCons globals injected at runtime.
Import: Any
Return: Any
env: Any

Import("env")

if env.IsIntegrationDump() or env.IsCleanTarget():
    Return()

frame = inspect.currentframe()
assert frame is not None
script_name = os.path.basename(inspect.getfile(frame))
print(f"[{script_name}] Start")

static_dir = os.path.join(env.get("PROJECT_SRC_DIR"), "static")

logo_src = os.path.join(env.get("PROJECT_DIR"), "logo.svg")
logo_dst = os.path.join(static_dir, "logo.svg")
shutil.copy2(logo_src, logo_dst)
print(f"[{script_name}] Copied logo.svg from project root to src/static/")

assert os.path.exists(static_dir), f"[{script_name}] Static directory '{static_dir}' does not exist"

files = sorted(f for f in os.listdir(static_dir) if os.path.isfile(os.path.join(static_dir, f)))

MIME = {
    ".css": "text/css",
    ".html": "text/html",
    ".json": "application/json",
    ".mjs": "application/javascript",
    ".svg": "image/svg+xml",
}


def sym(filename: str) -> str:
    return re.sub(r"[^\w]", "_", filename)


out_path = os.path.join(env.get("PROJECT_SRC_DIR"), "_static_files.h")
with open(out_path, "w") as f:
    f.write("// AUTO-GENERATED - do not edit; regenerated by embed_static.py at build time.\n\n")
    for name in files:
        f.write(f'INCBIN({sym(name)}, "src/static/{name}");\n')
    f.write("\nstatic const StaticFile STATIC_CATALOG[] = {\n")
    for name in files:
        ext = os.path.splitext(name)[1]
        mime = MIME.get(ext, "application/octet-stream")
        s = sym(name)
        f.write(f'    {{"{name}", "{mime}", {s}_data, {s}_size}},\n')
    f.write("};\n\n")

env.Append(EMBED_BINARYFILES=[os.path.join("src", "static", f) for f in files])

print(f"[{script_name}] Dynamically embedded {len(files)} assets from src/static.")
