#!/usr/bin/env python3
"""
Embed all files in static/ into the firmware as gzip-compressed binary assets,
and generate src/_static_files.h with declarations and a catalog for runtime access.
"""

import gzip
import hashlib
import inspect
import os
import re
import time
from typing import Any

# PlatformIO/SCons globals injected at runtime.
Import: Any
Return: Any
env: Any

Import("env")

if env.IsIntegrationDump() or env.IsCleanTarget():
    Return()

frame = inspect.currentframe()
assert frame is not None
script_name = os.path.basename(inspect.getfile(frame))
print(f"[{script_name}] Start")
start = time.perf_counter()

source_dir = os.path.join(env.get("PROJECT_DIR"), "static")
out_dir = os.path.join(env.get("PROJECT_SRC_DIR"), "static")
os.makedirs(out_dir, exist_ok=True)

assert os.path.exists(source_dir), f"[{script_name}] Source directory '{source_dir}' does not exist"

source_files = sorted(f for f in os.listdir(source_dir) if os.path.isfile(os.path.join(source_dir, f)))

# Logos live in the project root, not in static/.
ROOT_ASSETS = ["logo.svg", "logo.png"]

MIME = {
    ".css": "text/css",
    ".html": "text/html",
    ".json": "application/json",
    ".mjs": "application/javascript",
    ".png": "image/png",
    ".svg": "image/svg+xml",
}


def sym(filename: str) -> str:
    return re.sub(r"[^\w]", "_", filename)


# Collect all assets: (name, src_path)
all_assets: list[tuple[str, str]] = [(name, os.path.join(source_dir, name)) for name in source_files]
for root_asset in ROOT_ASSETS:
    root_path = os.path.join(env.get("PROJECT_DIR"), root_asset)
    if os.path.exists(root_path):
        all_assets.append((root_asset, root_path))
        print(f"[{script_name}] Including {root_asset} from project root")
all_assets.sort(key=lambda x: x[0])

# Compute hash of all source file names + ungzipped contents. Used to skip
# the gzip + header rewrite when nothing has actually changed — avoids mtime
# bumps on the .gz files (which would invalidate every env's build cache).
digest = hashlib.md5()
for name, src_path in all_assets:
    digest.update(name.encode())
    with open(src_path, "rb") as fh:
        digest.update(fh.read())
content_hash = digest.hexdigest()

out_path = os.path.join(env.get("PROJECT_SRC_DIR"), "_static_files.h")
hash_marker = f"// Content hash: {content_hash}\n"

# If the existing header already carries this hash, and every .gz output is
# present, nothing to do — just tell PIO what to embed and exit.
up_to_date = False
if os.path.exists(out_path):
    with open(out_path) as existing_fh:
        if hash_marker in existing_fh.read():
            up_to_date = all(os.path.exists(os.path.join(out_dir, name + ".gz")) for name, _ in all_assets)

if up_to_date:
    print(f"[{script_name}] Up to date, skipping gzip + header rewrite.")
else:
    # Gzip each file into out_dir.
    total_size = 0
    total_gz_size = 0
    for name, src_path in all_assets:
        gz_path = os.path.join(out_dir, name + ".gz")
        with open(src_path, "rb") as fin:
            data = fin.read()
        with gzip.open(gz_path, "wb", compresslevel=9) as fout:
            fout.write(data)
        gz_size = os.path.getsize(gz_path)
        ratio = gz_size / len(data) * 100 if data else 0
        print(f"[{script_name}] {name}: {len(data)} B → {gz_size} B ({ratio:.0f}%)")
        total_size += len(data)
        total_gz_size += gz_size
    total_ratio = total_gz_size / total_size * 100 if total_size else 0
    print(f"[{script_name}] Total size: {total_size} B → {total_gz_size} B ({total_ratio:.0f}%)")

    with open(out_path, "w") as f:
        f.write("// AUTO-GENERATED - do not edit; regenerated by embed_static.py at build time.\n")
        f.write(hash_marker)
        f.write("\n")
        for name, _ in all_assets:
            f.write(f'INCBIN({sym(name)}, "src/static/{name}.gz");\n')
        f.write("\nstatic const StaticFile STATIC_CATALOG[] = {\n")
        for name, _ in all_assets:
            ext = os.path.splitext(name)[1]
            mime = MIME.get(ext, "application/octet-stream")
            s = sym(name)
            f.write(f'    {{"{name}", "{mime}", {s}_data, {s}_size}},\n')
        f.write("};\n")

env.Append(EMBED_BINARYFILES=[os.path.join("src", "static", name + ".gz") for name, _ in all_assets])

elapsed_ms = (time.perf_counter() - start) * 1000
print(f"[{script_name}] Embedded {len(all_assets)} assets (gzip-compressed) from {source_dir} ({elapsed_ms:.0f} ms).")
