#!/usr/bin/env python3
"""
Read the version from pyproject.toml and generate src/_version.h.
Requires Python 3.11+ (uses tomllib from the standard library).
"""

import inspect
import os
import tomllib
from typing import Any

# PlatformIO/SCons globals injected at runtime.
Import: Any
Return: Any
env: Any

Import("env")

if env.IsIntegrationDump() or env.IsCleanTarget():
    Return()

frame = inspect.currentframe()
assert frame is not None
script_name = os.path.basename(inspect.getfile(frame))
print(f"[{script_name}] Start")

pyproject_path = os.path.join(env.get("PROJECT_DIR"), "pyproject.toml")
with open(pyproject_path, "rb") as f:
    pyproject = tomllib.load(f)

version = pyproject["project"]["version"]

out_path = os.path.join(env.get("PROJECT_SRC_DIR"), "_version.h")
with open(out_path, "w") as f:
    f.write("// AUTO-GENERATED - do not edit; regenerated by generate_version.py at build time.\n\n")
    f.write("#pragma once\n\n")
    f.write(f'#define FIRMWARE_VERSION "{version}"\n')

print(f"[{script_name}] Wrote {os.path.relpath(out_path, env.get('PROJECT_DIR'))} (version {version})")
