#!/usr/bin/env -S uv run
"""
fake_server.py — KikkerX development HTTP server.

Scans src/static/*.h on every request — no hardcoded catalog.
Static files are re-read each time so edits take effect on browser reload.

Usage:
    ./fake_server.py [--port PORT] [--board BOARD]

    --port PORT     Port to listen on (default: 8080)
    --board BOARD   Simulate a specific board's feature set:
                      timercam  — LED + battery enabled (default)
                      wrovercam — LED + battery disabled

Requires Pillow for animated camera images:
    pip install Pillow
Without Pillow, camera endpoints return a static 1×1 placeholder JPEG.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import math
import mimetypes
import os
import random
import re
import socket
import sys
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from socketserver import ThreadingMixIn
from typing import Any
from urllib.parse import urlparse, parse_qs

try:
    from PIL import Image, ImageDraw, ImageFilter, ImageChops
    import numpy as np
except ImportError as e:
    print(f"Error: {e}")
    sys.exit("Package not installed. Run:  uv run fake_server.py")

mimetypes.add_type("text/javascript", ".mjs")

# ---------------------------------------------------------------------------
# Board feature table
# ---------------------------------------------------------------------------

_BOARD_FEATURES: dict[str, dict[str, Any]] = {
    "timercam": {"board": "M5Stack Timer Camera X", "led": True, "battery": True},
    "wrovercam": {"board": "ESP32-WROVER-CAM", "led": True, "battery": False},
}

# Populated at startup from --board argument; defaults to all features enabled.
_features: dict[str, Any] = {"board": "KikkerX (dev server)", "led": True, "battery": True}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(SCRIPT_DIR, "src", "static")

# ---------------------------------------------------------------------------
# config.json loader
# ---------------------------------------------------------------------------


def _load_config() -> dict[str, Any]:
    """
    Loads the merged config into a Python dict.

    Tries src/_config.json first (generated by last build), then falls
    back to configs/default_config.json.  Prints which file was loaded.
    """
    built_config = os.path.join(SCRIPT_DIR, "src", "_config.json")
    default_config = os.path.join(SCRIPT_DIR, "configs", "default_config.json")

    def load(path: str) -> dict[str, Any]:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
            print(f"Config loaded from {os.path.relpath(path, SCRIPT_DIR)}")
            return data

    try:
        return load(built_config)
    except FileNotFoundError:
        print(f"Built config not found at {os.path.relpath(built_config, SCRIPT_DIR)}, falling back to default config")
        return load(default_config)


_CONFIG = _load_config()


# ---------------------------------------------------------------------------
# Auth — read from parsed config
# ---------------------------------------------------------------------------


def _check_auth(handler: BaseHTTPRequestHandler) -> bool:
    """Returns True if the request passes Basic Auth (or auth is unconfigured)."""
    auth = _CONFIG.get("auth") or {}
    username = auth.get("username")
    if username is None:
        return True
    header = handler.headers.get("Authorization", "")
    if not header.startswith("Basic "):
        return False
    try:
        decoded = base64.b64decode(header[6:]).decode("utf-8", errors="replace")
    except Exception:
        return False
    colon = decoded.find(":")
    if colon < 0:
        return False
    req_user, req_pass = decoded[:colon], decoded[colon + 1 :]
    if req_user != username:
        return False
    return hashlib.sha256(req_pass.encode()).hexdigest() == (auth.get("pass_sha256") or "")


RESOLUTIONS = {
    "QQVGA": (160, 120),
    "QVGA": (320, 240),
    "CIF": (400, 296),
    "VGA": (640, 480),
    "SVGA": (800, 600),
    "XGA": (1024, 768),
    "SXGA": (1280, 1024),
    "UXGA": (1600, 1200),
}

# ---------------------------------------------------------------------------
# .h file loader — discovers files dynamically, no hardcoded catalog
# ---------------------------------------------------------------------------


def _static_files() -> dict[str, str]:
    """Returns {filename: path} for every *.h file in STATIC_DIR."""
    result = {}
    try:
        for entry in os.scandir(STATIC_DIR):
            if entry.name.endswith(".h") and entry.is_file():
                basename = entry.name[:-2]  # strip .h
                result[basename] = entry.path
    except FileNotFoundError:
        pass
    return result


def load_static(basename: str) -> tuple[bytes | None, str | None]:
    """
    Loads static content as bytes. Re-reads on every call.

    Checks for an actual file in STATIC_DIR first, then falls back to parsing
    the companion .h file."""
    actual = os.path.join(STATIC_DIR, basename)
    if os.path.isfile(actual):
        with open(actual, "rb") as f:
            data = f.read()
        ctype, _ = mimetypes.guess_type(basename)
        return data, ctype or "application/octet-stream"

    files = _static_files()
    path = files.get(basename)
    if path is None:
        return None, None
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    m = re.search(r'R"(\w*)\((.*?)\)\1"', text, re.DOTALL)
    content = m.group(2) if m else text
    ctype, _ = mimetypes.guess_type(basename)
    return content.encode("utf-8"), ctype or "application/octet-stream"


# ---------------------------------------------------------------------------
# Image generation — "Kikker's Pond at Night"
# ---------------------------------------------------------------------------

_SERVER_START = time.monotonic()
_led_state = False

# Orb definitions: (base_x, base_y, size_frac, rgb, orbit_speed, phase)
_ORBS = [
    (0.30, 0.48, 0.040, (0, 210, 155), 0.333, 0.00),  # teal
    (0.68, 0.55, 0.030, (50, 220, 50), 0.250, 1.31),  # lime
    (0.50, 0.26, 0.045, (20, 130, 240), 0.417, 2.62),  # electric blue
    (0.17, 0.70, 0.025, (230, 110, 0), 0.293, 4.10),  # amber
    (0.83, 0.22, 0.030, (170, 0, 230), 0.367, 5.50),  # violet
    (0.60, 0.78, 0.022, (0, 190, 240), 0.273, 3.35),  # cyan
]


def _add_glow(img: Image.Image, cx: int, cy: int, r: int, color: tuple[int, int, int]) -> None:
    """Additively blends a soft glowing orb into img using crop-blur-paste."""
    W, H = img.size
    margin = r * 4 + 4
    x0, y0 = max(0, cx - margin), max(0, cy - margin)
    x1, y1 = min(W, cx + margin), min(H, cy + margin)
    if x1 <= x0 or y1 <= y0:
        return
    lx, ly = cx - x0, cy - y0  # local coords within patch

    def _apply_patch(patch: Image.Image, blur: float) -> None:
        nonlocal img
        patch = patch.filter(ImageFilter.GaussianBlur(radius=max(1, blur)))
        crop = img.crop((x0, y0, x1, y1))
        img.paste(ImageChops.add(crop, patch), (x0, y0))

    pw, ph = x1 - x0, y1 - y0

    # Outer diffuse halo
    halo = Image.new("RGB", (pw, ph))
    ImageDraw.Draw(halo).ellipse(
        [lx - r * 2, ly - r * 2, lx + r * 2, ly + r * 2],
        fill=(color[0] // 5, color[1] // 5, color[2] // 5),
    )
    _apply_patch(halo, r)

    # Bright inner core
    core = Image.new("RGB", (pw, ph))
    ImageDraw.Draw(core).ellipse([lx - r, ly - r, lx + r, ly + r], fill=color)
    _apply_patch(core, r // 2)

    # Sharp pinpoint centre
    dot_r = max(1, r // 4)
    bright = (min(255, color[0] + 110), min(255, color[1] + 110), min(255, color[2] + 110))
    ImageDraw.Draw(img).ellipse([cx - dot_r, cy - dot_r, cx + dot_r, cy + dot_r], fill=bright)


def _make_pond_jpeg(width: int, height: int, t: float) -> bytes:
    """Returns JPEG bytes: an animated bioluminescent pond scene."""
    # ------------------------------------------------------------------ #
    # Background: deep-water gradient (black → dark teal → near-black)   #
    # Rendered at reduced size, then scaled — cheap and smooth.          #
    # ------------------------------------------------------------------ #
    BW = min(width, 96)
    BH = max(1, BW * height // width)

    bg_data: list[tuple[int, int, int]] = []
    for y in range(BH):
        fy = y / BH
        # Subtle luminous band around 35 % depth (water surface reflection)
        band = math.exp(-((fy - 0.35) ** 2) / 0.015) * 0.35
        # Slow horizontal shimmer using sine
        shimmer = 0.04 * math.sin(fy * 18 + t * 0.2)
        lum = band + shimmer
        r = int(max(0, min(255, 3 + lum * 30)))
        g = int(max(0, min(255, 18 + lum * 90 + 10 * (1 - fy))))
        b = int(max(0, min(255, 40 + lum * 80 + 20 * (1 - fy))))
        bg_data.extend([(r, g, b)] * BW)

    img = Image.new("RGB", (BW, BH))
    img.putdata(bg_data)
    img = img.resize((width, height), Image.Resampling.BILINEAR)

    # ------------------------------------------------------------------ #
    # Caustic shimmer lines across the lower half                        #
    # ------------------------------------------------------------------ #
    draw = ImageDraw.Draw(img)
    for i in range(12):
        phase = i / 12
        y_base = int((0.55 + 0.35 * phase) * height)
        amp = int(0.006 * height * (1 + math.sin(t * 0.133 + phase * 7)))
        x_step = max(1, width // 80)
        pts = []
        for x in range(0, width + x_step, x_step):
            fx = x / width
            dy = int(amp * math.sin(fx * 12 + t * 0.367 + phase * 5))
            pts.append((x, y_base + dy))
        if len(pts) >= 2:
            alpha = int(18 * (1 - phase))
            draw.line(pts, fill=(0, alpha * 4, alpha * 2), width=1)

    # ------------------------------------------------------------------ #
    # Glowing orbs                                                       #
    # ------------------------------------------------------------------ #
    for bx, by, sf, color, sp, ph in _ORBS:
        cx = int((bx + 0.055 * math.sin(t * sp + ph)) * width)
        cy = int((by + 0.038 * math.cos(t * sp * 0.8 + ph)) * height)
        r = max(3, int(sf * min(width, height)))
        _add_glow(img, cx, cy, r, color)

    # ------------------------------------------------------------------ #
    # Expanding ripple rings from centre (pond-drop effect)              #
    # ------------------------------------------------------------------ #
    draw = ImageDraw.Draw(img)
    cx0, cy0 = width // 2, int(height * 0.45)
    for i in range(7):
        phase = (t * 0.073 + i / 7) % 1.0
        rr = int(phase * min(width, height) * 0.48)
        fade = int(100 * (1 - phase) ** 2)
        if rr > 2:
            draw.ellipse(
                [cx0 - rr, cy0 - rr, cx0 + rr, cy0 + rr],
                outline=(0, min(255, fade * 3), fade),
                width=1,
            )

    # ------------------------------------------------------------------ #
    # Drifting fireflies / pollen                                        #
    # ------------------------------------------------------------------ #
    rng = random.Random(int(t * 0.133))  # advance slowly
    for _ in range(35):
        px = int(rng.random() * width)
        py = int(rng.random() * height)
        twinkle = 0.5 + 0.5 * math.sin(t * (0.333 + rng.random()) + rng.random() * 6.28)
        brt = int(80 + 140 * twinkle)
        hue = rng.random()
        fr = int(brt * (0.4 + 0.6 * math.sin(hue * 6.28 + 1.0)))
        fg = int(brt * (0.4 + 0.6 * math.sin(hue * 6.28 + 2.5)))
        fb = int(brt * (0.4 + 0.6 * math.sin(hue * 6.28 + 0.0)))
        draw.ellipse(
            [px - 1, py - 1, px + 1, py + 1],
            fill=(min(255, fr), min(255, fg), min(255, fb)),
        )

    # ------------------------------------------------------------------ #
    # HUD overlay                                                        #
    # ------------------------------------------------------------------ #
    label = f"KikkerX  {width}\u00d7{height}  {time.strftime('%H:%M:%S')}"
    draw.text((8, 8), label, fill=(180, 200, 200))

    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=85)
    return buf.getvalue()


def _make_synthwave_jpeg(width: int, height: int, t: float) -> bytes:
    """Returns JPEG bytes: an animated retrowave synthwave grid scene."""
    horizon_y = int(height * 0.42)

    # ------------------------------------------------------------------ #
    # Background gradient (low-res, scaled up)                           #
    # Sky: deep blue-purple darkening upward                             #
    # Ground: dark with a warm magenta bleed near the horizon            #
    # ------------------------------------------------------------------ #
    BW = min(width, 160)
    BH = max(1, BW * height // width)
    h_frac = horizon_y / height

    bg_data: list[tuple[int, int, int]] = []
    for y in range(BH):
        fy = y / BH
        if fy < h_frac:
            sk = fy / h_frac  # top → horizon: near-black to deep indigo
            r = int(10 + 90 * sk * sk)
            g = int(4 * sk)
            b = int(52 - 12 * sk)
        else:
            gr = (fy - h_frac) / (1 - h_frac)  # 0=horizon, 1=bottom
            r = int(70 * (1 - gr) ** 1.5)
            g = 0
            b = int(22 * (1 - gr) * (1 - gr))
        bg_data.extend([(r, g, b)] * BW)

    img = Image.new("RGB", (BW, BH))
    img.putdata(bg_data)
    img = img.resize((width, height), Image.Resampling.BILINEAR)

    vp_x = width // 2

    # ------------------------------------------------------------------ #
    # Retrowave sun: gradient disc with dark horizontal stripes          #
    # ------------------------------------------------------------------ #
    sun_r = max(8, min(width, height) // 5)
    sr = int(sun_r * (1.0 + 0.025 * math.sin(t * 0.3)))
    stripe_h = max(2, sr // 7)
    draw = ImageDraw.Draw(img)
    for dy in range(-sr, sr + 1):
        sy = horizon_y + dy
        if sy < 0 or sy >= height:
            continue
        chord = int(math.sqrt(max(0, sr * sr - dy * dy)))
        if chord <= 0:
            continue
        fy = (dy + sr) / (2 * sr)  # 0=top, 1=bottom
        in_stripe = (dy > 0) and ((dy // stripe_h) % 2 == 0)
        if in_stripe:
            col = (8, 0, 20)
        else:
            col = (
                min(255, int(220 + 35 * (1 - fy))),
                int(40 + 120 * (1 - fy) ** 2),
                int(170 * (1 - fy) ** 1.5),
            )
        draw.line([(vp_x - chord, sy), (vp_x + chord, sy)], fill=col)

    _add_glow(img, vp_x, horizon_y, sr, (255, 60, 180))
    draw = ImageDraw.Draw(img)

    # ------------------------------------------------------------------ #
    # Grid: vertical fan lines radiating from vanishing point            #
    # ------------------------------------------------------------------ #
    n_vlines = 20
    for i in range(n_vlines + 1):
        fi = i / n_vlines
        bx = int(fi * width)
        fade = max(0.0, 1.0 - abs(fi - 0.5) * 1.3)
        col = (int(190 * fade), 0, int(155 * fade))
        draw.line([(vp_x, horizon_y), (bx, height - 1)], fill=col, width=1)

    # ------------------------------------------------------------------ #
    # Grid: horizontal perspective lines scrolling toward the viewer     #
    # ------------------------------------------------------------------ #
    n_hlines = 14
    scroll = (t * 0.175) % 1.0
    for i in range(n_hlines + 2):
        depth = ((i + scroll) / n_hlines) % 1.0
        if depth <= 0:
            continue
        y = int(horizon_y + (height - horizon_y) * (depth**0.55))
        if y <= horizon_y or y >= height:
            continue
        fade = depth**0.6
        draw.line(
            [(0, y), (width - 1, y)],
            fill=(0, int(210 * fade), int(150 * fade)),
            width=1,
        )

    # ------------------------------------------------------------------ #
    # Stars: fixed positions, twinkling                                  #
    # ------------------------------------------------------------------ #
    rng = random.Random(7)
    for _ in range(220):
        px = int(rng.random() * width)
        py = int(rng.random() * horizon_y)
        brt = int(80 + 175 * (0.5 + 0.5 * math.sin(t * (0.75 + rng.random() * 1.75) + rng.random() * 6.28)))
        h = rng.random()
        sc_r = min(255, int(brt * (0.75 + 0.25 * math.sin(h * 8 + 1.0))))
        sc_g = min(255, int(brt * (0.65 + 0.35 * math.cos(h * 7 + 0.5))))
        sc_b = min(255, int(brt * (0.90 + 0.10 * math.sin(h * 9 + 2.0))))
        draw.point((px, py), fill=(sc_r, sc_g, sc_b))

    # ------------------------------------------------------------------ #
    # HUD overlay                                                        #
    # ------------------------------------------------------------------ #
    label = f"KikkerX  {width}\u00d7{height}  {time.strftime('%H:%M:%S')}"
    draw.text((8, 8), label, fill=(210, 80, 255))

    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=85)
    return buf.getvalue()


def _make_julia_jpeg(width: int, height: int, t: float) -> bytes:
    """
    Returns JPEG bytes: an animated Julia set fractal garden.

    c traces a circle of radius 0.7885 in the complex plane, visiting
    spirals → coral tendrils → fern fronds → snowflakes → back.
    Rendered at full output resolution via numpy vectorisation.
    """
    MAX_ITER = 100
    R_SQ = 256.0  # large escape radius improves smooth colouring

    cr = 0.7885 * math.cos(t * 0.0267)
    ci = 0.7885 * math.sin(t * 0.0267)

    # Colour cycle speed independent of the shape-morph speed.
    col_shift = t * 0.00417

    CW, CH = width, height
    zr_a, zi_a = np.meshgrid(
        np.linspace(-1.4, 1.4, CW, dtype=np.float32),
        np.linspace(-1.4 * CH / CW, 1.4 * CH / CW, CH, dtype=np.float32),
    )

    escaped_n = np.full((CH, CW), MAX_ITER, dtype=np.int32)
    escaped_mod = np.ones((CH, CW), dtype=np.float32)
    alive = np.ones((CH, CW), dtype=bool)

    for n in range(MAX_ITER):
        zr2 = zr_a * zr_a
        zi2 = zi_a * zi_a
        just_escaped = alive & (zr2 + zi2 >= R_SQ)
        escaped_n[just_escaped] = n
        escaped_mod[just_escaped] = (zr2 + zi2)[just_escaped]
        alive &= ~just_escaped
        new_zr = zr2 - zi2 + cr
        new_zi = 2.0 * zr_a * zi_a + ci
        zr_a = np.where(alive, new_zr, zr_a)
        zi_a = np.where(alive, new_zi, zi_a)
        if not alive.any():
            break

    interior = escaped_n == MAX_ITER
    log2_mod = np.log(np.maximum(escaped_mod, 1e-10)) * 1.4427
    log2_log2 = np.log(np.maximum(log2_mod, 1e-10)) * 1.4427
    smooth = np.where(interior, 0.0, escaped_n.astype(np.float32) - log2_log2)

    hue = (smooth * 0.04 + col_shift) % 1.0
    h = (hue * 6.2832).astype(np.float32)
    r_ch = np.clip(10 + 220 * np.maximum(0.0, np.sin(h + 0.00)) ** 2, 0, 255).astype(np.uint8)
    g_ch = np.clip(5 + 240 * np.maximum(0.0, np.sin(h + 2.09)) ** 2, 0, 255).astype(np.uint8)
    b_ch = np.clip(20 + 210 * np.maximum(0.0, np.sin(h + 4.19)) ** 2, 0, 255).astype(np.uint8)
    r_ch[interior] = 0
    g_ch[interior] = 8
    b_ch[interior] = 4

    img = Image.fromarray(np.stack([r_ch, g_ch, b_ch], axis=2), "RGB")

    # Additive glow — makes the bright filaments feel luminous.
    glow = img.filter(ImageFilter.GaussianBlur(radius=2))
    img = ImageChops.add(img, glow)

    draw = ImageDraw.Draw(img)
    label = f"KikkerX  {width}\u00d7{height}  {time.strftime('%H:%M:%S')}"
    draw.text((8, 8), label, fill=(160, 255, 180))

    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=85)
    return buf.getvalue()


def _make_3d_jpeg(width: int, height: int, t: float) -> bytes:
    """
    Returns JPEG bytes: wireframe armillary sphere — six orbital rings + central icosahedron.

    Six great-circle rings (three cardinal + three diagonal) enclose a regular
    icosahedron at the centre.  The whole structure rotates slowly as one rigid
    body.  Edges are depth-cued: near lines are warm ivory, far lines fade to
    near-black.  A subtle bloom pass adds the impression of luminous wire.
    Runs at full output resolution — wireframe projection is orders of magnitude
    faster than the previous raymarcher.
    """
    # ------------------------------------------------------------------ #
    # Icosahedron — 12 vertices, 30 edges                                #
    # ------------------------------------------------------------------ #
    _phi = (1.0 + math.sqrt(5.0)) / 2.0
    _circ = math.sqrt(1.0 + _phi * _phi)  # circumradius of unit-edge icos
    _s = 0.82 / _circ  # scale so circumradius = 0.82
    icos_verts = [
        (0.0, _s, _s * _phi),
        (0.0, -_s, _s * _phi),
        (0.0, _s, -_s * _phi),
        (0.0, -_s, -_s * _phi),
        (_s, _s * _phi, 0.0),
        (-_s, _s * _phi, 0.0),
        (_s, -_s * _phi, 0.0),
        (-_s, -_s * _phi, 0.0),
        (_s * _phi, 0.0, _s),
        (-_s * _phi, 0.0, _s),
        (_s * _phi, 0.0, -_s),
        (-_s * _phi, 0.0, -_s),
    ]
    _edge_sq = (2.0 * _s * 1.05) ** 2  # edge-length² with 5 % tolerance
    icos_edges = [
        (i, j)
        for i in range(12)
        for j in range(i + 1, 12)
        if sum((icos_verts[i][k] - icos_verts[j][k]) ** 2 for k in range(3)) < _edge_sq
    ]

    # ------------------------------------------------------------------ #
    # Six rings: three cardinal great circles + three diagonal ones      #
    # ------------------------------------------------------------------ #
    _h = math.sqrt(2.0) / 2.0
    ring_normals = [
        (0.0, 1.0, 0.0),  # equatorial
        (1.0, 0.0, 0.0),  # meridian 1
        (0.0, 0.0, 1.0),  # meridian 2
        (_h, _h, 0.0),  # 45° between equatorial and meridian 1
        (_h, 0.0, _h),  # 45° between equatorial and meridian 2
        (0.0, _h, _h),  # 45° between meridian 1 and meridian 2
    ]
    RING_R = 1.52
    RING_SEGS = 80

    ring_segs_3d: list[tuple[tuple[float, float, float], tuple[float, float, float]]] = []  # (point_a, point_b)
    for nx, ny, nz in ring_normals:
        # Build an orthonormal basis for the ring's plane.
        if abs(nz) < 0.9:
            ux, uy, uz = -ny, nx, 0.0
        else:
            ux, uy, uz = 0.0, -nz, ny
        ul = math.sqrt(ux * ux + uy * uy + uz * uz)
        ux /= ul
        uy /= ul
        uz /= ul
        vx = ny * uz - nz * uy
        vy = nz * ux - nx * uz
        vz = nx * uy - ny * ux
        pts = [
            (
                RING_R * (math.cos(2.0 * math.pi * k / RING_SEGS) * ux + math.sin(2.0 * math.pi * k / RING_SEGS) * vx),
                RING_R * (math.cos(2.0 * math.pi * k / RING_SEGS) * uy + math.sin(2.0 * math.pi * k / RING_SEGS) * vy),
                RING_R * (math.cos(2.0 * math.pi * k / RING_SEGS) * uz + math.sin(2.0 * math.pi * k / RING_SEGS) * vz),
            )
            for k in range(RING_SEGS)
        ]
        ring_segs_3d.extend(zip(pts, pts[1:] + [pts[0]]))

    # ------------------------------------------------------------------ #
    # Global rotation — Y spin + two-frequency precession on X and Z     #
    # ------------------------------------------------------------------ #
    gy = t * 0.46
    gx = 0.30 * math.sin(t * 0.21) + 0.10 * math.sin(t * 0.33)
    gz = 0.14 * math.sin(t * 0.18) + 0.05 * math.sin(t * 0.29)
    cy, sy = math.cos(gy), math.sin(gy)
    cx, sx = math.cos(gx), math.sin(gx)
    cz, sz = math.cos(gz), math.sin(gz)

    def rotate(x: float, y: float, z: float) -> tuple[float, float, float]:
        x, z = cy * x + sy * z, -sy * x + cy * z
        y, z = cx * y - sx * z, sx * y + cx * z
        x, y = cz * x - sz * y, sz * x + cz * y
        return x, y, z

    # ------------------------------------------------------------------ #
    # Perspective projection                                             #
    # ------------------------------------------------------------------ #
    CAM_Z = 5.2  # camera sits at z = -CAM_Z looking toward +z
    FOCAL = 3.8
    W_HALF = 1.22
    H_HALF = W_HALF * height / width

    def project(x: float, y: float, z: float) -> tuple[int, int]:
        cz_cam = z + CAM_Z
        if cz_cam < 0.1:
            cz_cam = 0.1
        xs = FOCAL * x / cz_cam
        ys = FOCAL * y / cz_cam
        px = int((xs + W_HALF) / (2.0 * W_HALF) * width)
        py = int((H_HALF - ys) / (2.0 * H_HALF) * height)
        return px, py

    # ------------------------------------------------------------------ #
    # Build segment list with world-space depth for sorting + cuing      #
    # ------------------------------------------------------------------ #
    all_segs = []  # (z_avg, proj_a, proj_b, is_icos)

    for pa, pb in ring_segs_3d:
        ra = rotate(*pa)
        rb = rotate(*pb)
        all_segs.append(((ra[2] + rb[2]) * 0.5, project(*ra), project(*rb), False))

    riv = [rotate(*v) for v in icos_verts]
    for i, j in icos_edges:
        pa, pb = riv[i], riv[j]
        all_segs.append(((pa[2] + pb[2]) * 0.5, project(*pa), project(*pb), True))

    all_segs.sort(reverse=True)  # farthest first (painter's algorithm)
    Z_NEAR, Z_FAR = -RING_R, RING_R  # world-z extent of the scene

    # ------------------------------------------------------------------ #
    # Background — faint radial glow so the sphere floats in soft space  #
    # Built at low resolution and upscaled; all C-side, very fast.       #
    # ------------------------------------------------------------------ #
    _BW, _BH = 64, 48
    bg = Image.new("RGB", (_BW, _BH), (4, 4, 6))
    _bg_draw = ImageDraw.Draw(bg)
    # Warm amber centre glow — bright enough to survive the heavy blur
    _bg_draw.ellipse((_BW // 5, _BH // 5, 4 * _BW // 5, 4 * _BH // 5), fill=(105, 72, 38))
    bg = bg.filter(ImageFilter.GaussianBlur(radius=14))
    img = bg.resize((width, height), Image.Resampling.BILINEAR)

    # ------------------------------------------------------------------ #
    # Render                                                             #
    # ------------------------------------------------------------------ #
    draw = ImageDraw.Draw(img)

    for z_avg, (px0, py0), (px1, py1), is_icos in all_segs:
        # depth: 1.0 = nearest to camera, 0.0 = farthest
        depth = (Z_FAR - z_avg) / (Z_FAR - Z_NEAR)
        depth = max(0.0, min(1.0, depth))
        d2 = depth * depth
        if is_icos:
            # Icosahedron: warm amber-gold, distinct from the rings
            r = int(40 + 208 * d2)
            g = int(34 + 178 * d2)
            b = int(22 + 130 * d2)
        else:
            # Rings: cool off-white parchment
            r = int(30 + 195 * d2)
            g = int(30 + 188 * d2)
            b = int(28 + 178 * d2)
        draw.line((px0, py0, px1, py1), fill=(r, g, b))

    # ------------------------------------------------------------------ #
    # Bloom — a tinted blur blended back in to suggest glowing wire      #
    # ------------------------------------------------------------------ #
    glow = img.filter(ImageFilter.GaussianBlur(radius=2))
    img = ImageChops.add(img, ImageChops.multiply(glow, Image.new("RGB", img.size, (72, 66, 52))))

    draw = ImageDraw.Draw(img)
    draw.text((8, 8), f"KikkerX  {width}\u00d7{height}  {time.strftime('%H:%M:%S')}", fill=(138, 128, 100))

    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=85)
    return buf.getvalue()


def _make_black_jpeg(width: int, height: int, t: float) -> bytes:
    """Return JPEG bytes: black frame with info text only (brightness=-2, reserved)."""
    img = Image.new("RGB", (width, height), (0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.text((8, 8), f"KikkerX  {width}\u00d7{height}  {time.strftime('%H:%M:%S')}", fill=(60, 60, 60))
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=85)
    return buf.getvalue()


# Direct mapping from OV3660 brightness value (−2 … +2) to scene function.
_SCENE_FUNCS = {
    -2: _make_black_jpeg,  # (reserved — black)
    -1: _make_3d_jpeg,  # Armillary Sphere (wireframe)
    0: _make_pond_jpeg,  # Kikker's Pond at Night
    1: _make_synthwave_jpeg,  # Retrowave Grid
    2: _make_julia_jpeg,  # Fractal Garden (Julia set)
}


def make_jpeg(width: int, height: int, scene: int = 0) -> bytes:
    t = time.monotonic() - _SERVER_START
    fn = _SCENE_FUNCS.get(scene, _make_pond_jpeg)
    return fn(width, height, t)


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------


class KikkerXHandler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def setup(self) -> None:
        self.request.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        super().setup()

    def log_message(self, fmt: str, *args: Any) -> None:
        print(f"  {self.address_string()}  {fmt % args}")

    def _deny_auth(self) -> None:
        self.send_response(401)
        self.send_header("WWW-Authenticate", 'Basic realm="KikkerX"')
        self.send_header("Content-Length", "0")
        self.end_headers()

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path != "/manifest.json" and not _check_auth(self):
            self._deny_auth()
            return
        path = parsed.path
        qs = parse_qs(parsed.query)

        def qp(key: str, default: str = "") -> str:
            return qs.get(key, [default])[0]

        # --- Static file routing ---
        # /         → index.html
        # /stream   → stream.html   (extensionless paths get .html appended)
        # /foo.mjs  → foo.mjs       (verbatim)
        if path == "/":
            lookup = "index.html"
        else:
            bare = path.lstrip("/")
            if "." not in bare:
                bare += ".html"
            lookup = bare

        content, ctype = load_static(lookup)
        if content is not None:
            body = content
            is_text = (ctype or "").startswith("text/")
            ct = (ctype or "application/octet-stream") + ("; charset=utf-8" if is_text else "")
            self.send_response(200)
            self.send_header("Content-Type", ct)
            self.send_header("Cache-Control", "no-cache")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        # --- API routes ---
        if path == "/api/logs":
            self._send_text(
                "Camera init OK\n"
                "Scanning WiFi...\n"
                "Connecting to HomeNet (RSSI -52)...\n"
                "Connected: HomeNet  IP: 192.168.1.99  RSSI: -52\n"
                "Camera server ready at http://192.168.1.99/ (http://kikker-x.local/)\n"
                "GET /\n"
                "→ 200 index.html\n"
                "GET /style.css\n"
                "→ 200 style.css\n"
                "GET /logo.svg\n"
                "→ 200 logo.svg\n"
                "GET /api/status\n"
                "→ 200 status 4132mV 87% rssi=-52\n"
                "GET /api/led\n"
                "→ 200 led state=off\n"
                "GET /api/logs\n"
                "→ 200 logs 312 bytes\n"
            )

        elif path == "/api/status":
            rssi = -58 + random.randint(-3, 3)
            data: dict[str, Any] = {
                "id": "c0ffeefacade",
                "wifi": {"mode": "station", "ssid": "FakeAP", "ip": "192.168.1.99", "rssi": rssi},
                "version": "1.0.0",
                "features": _features,
            }
            if _features["battery"]:
                voltage = 3850 + random.randint(-15, 15)
                data["battery"] = {"voltage": voltage, "level": 75}
            self._send_json(data)

        elif path == "/api/led":
            if not _features["led"]:
                self.send_error(404)
                return
            self._send_json({"state": _led_state})

        elif path == "/api/streamfps":
            self._send_json({"fps": 18.5, "active": True})

        elif path == "/api/cam/capture.jpg":
            w, h = RESOLUTIONS.get(qp("res", "UXGA").upper(), (1600, 1200))
            jpeg = make_jpeg(w, h, int(qp("brightness", "0")))
            self.send_response(200)
            self.send_header("Content-Type", "image/jpeg")
            self.send_header("Content-Length", str(len(jpeg)))
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            self.wfile.write(jpeg)

        elif path == "/api/cam/stream.mjpeg":
            w, h = RESOLUTIONS.get(qp("res", "VGA").upper(), (640, 480))
            self._serve_mjpeg(w, h, int(qp("brightness", "0")))

        else:
            self.send_error(404)

    def do_PATCH(self) -> None:
        if not _check_auth(self):
            self._deny_auth()
            return
        global _led_state
        parsed = urlparse(self.path)
        if parsed.path == "/api/led":
            if not _features["led"]:
                self.send_error(404)
                return
            length = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(length) or b"{}")
            if "state" in body:
                _led_state = bool(body["state"])
            self._send_json({"state": _led_state})
        else:
            self.send_error(405)

    def do_POST(self) -> None:
        if not _check_auth(self):
            self._deny_auth()
            return
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/api/restart":
            self._send_text("Restarting.")
            import threading

            def _restart() -> None:
                time.sleep(0.5)
                os.execv(sys.executable, [sys.executable] + sys.argv)

            threading.Thread(target=_restart, daemon=True).start()
        elif path == "/api/poweroff":
            self._send_text("Powering off.")
            import threading

            threading.Thread(target=self.server.shutdown, daemon=True).start()
        elif path == "/api/wifi/reconnect":
            self._send_text("Reconnecting to WiFi.")
        elif path == "/api/led/blink":
            if not _features["led"]:
                self.send_error(404)
                return
            length = int(self.headers.get("Content-Length", 0))
            self.rfile.read(length)  # consume body, blink not simulated
            self._send_text("OK")
        else:
            self.send_error(405)

    # ---- helpers ----

    def _send_json(self, data: Any) -> None:
        body = json.dumps(data).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_text(self, text: str) -> None:
        body = text.encode()
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _serve_mjpeg(self, width: int, height: int, scene: int = 0) -> None:
        self.send_response(200)
        self.send_header("Content-Type", "multipart/x-mixed-replace;boundary=frame")
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        try:
            while True:
                jpeg = make_jpeg(width, height, scene)
                self.wfile.write(
                    b"\r\n--frame\r\n"
                    b"Content-Type: image/jpeg\r\n"
                    b"Content-Length: " + str(len(jpeg)).encode() + b"\r\n\r\n" + jpeg
                )
                self.wfile.flush()
                time.sleep(1 / 30)  # ~30 FPS
        except (BrokenPipeError, ConnectionResetError, OSError):
            pass


class ThreadedHTTPServer(ThreadingMixIn, HTTPServer):
    """Each connection runs in its own thread (MJPEG + page loads concurrently)."""

    daemon_threads = True


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="KikkerX development HTTP server")
    parser.add_argument("--port", type=int, default=8080, help="Port to listen on (default: 8080)")
    parser.add_argument(
        "--board",
        choices=list(_BOARD_FEATURES.keys()),
        help="Simulate a specific board's feature set (default: all features enabled)",
    )
    args = parser.parse_args()

    if args.board:
        _features.update(_BOARD_FEATURES[args.board])
        print(f"Board: {args.board} — features: {_features}")
    else:
        print(f"Board: (default) — features: {_features}")

    httpd = ThreadedHTTPServer(("", args.port), KikkerXHandler)
    print(f"KikkerX dev server → http://localhost:{args.port}/")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")
