; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; Base configuration for KikkerX:
[kikker-x]
platform = espressif32
board = m5stack-timer-cam
framework = arduino

upload_speed = 115200
upload_flags =
    --before=default_reset
    --after=hard_reset
monitor_speed = 115200

lib_deps =
    m5stack/Timer-CAM
    alexiii/incbin
extra_scripts =
    pre:build_helpers/generate_version.py
    pre:build_helpers/embed_static.py
    pre:build_helpers/prepare_config.py


; Build with the default parameters.
[env:kikker-x-default]
extends = kikker-x
; The JSON file (or files) that are used as the config for the camera. If multiple files are
; provided, they are shallow merged (only top-level fields) with the later files taking
; precedence over the earlier ones. This allows to have e.g. a common config for WiFi credentials
; and separate configs for other settings.
custom_config_files = configs/default_config.json


[platformio]
; The gitignored configs/platformio.ini can define custom configurations, similar to the
; [env:kikker-x-default] above. See configs/platformio.ini.template for more information.
extra_configs = configs/platformio.ini
